select *
  from sistabgen
 where sistabcod = 500
   and sisdatcod in (171, 173, 174, 175, 176, 177, 178)
 order by sisdatcod;

select * from sistabgen;

-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '170', 'ESTADO DE GANANCIAS Y PERDIDAS FUNCION', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER', '4', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '171', 'ESTADO DE GANANCIAS Y PERDIDAS NATURALEZA', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER', '5', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '173', 'ESTADO DE GANANCIAS Y PERDIDAS NATURALEZA 3 ULT. AÑOS', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_TR', '5', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '174', 'ESTADO DE GANANCIAS Y PERDIDAS FUNCION TRIMESTRAL', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_TRM', '4', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '175', 'ESTADO DE GANANCIAS Y PERDIDAS NATURALEZA TRIMESTRAL', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_TRM', '5', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '176', 'ESTADO DE GANANCIAS Y PERDIDAS FUNCION ANUAL', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_ANUAL', '4', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '177', 'ESTADO DE GANANCIAS Y PERDIDAS NATURALEZA ANUAL', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_ANUAL', '5', null);
-- INSERT INTO PEVISA.SISTABGEN (SISTABCOD, SISDATCOD, SISDATDES, SISDATABV, SISMODO, SISDATARP, SISP_RCUENTA, SISP_NPDF) VALUES (500, '178', 'ESTADO DE GANANCIAS Y PERDIDAS FUNCION ANUAL (REAL)', 'GER_CC_VARIOS', 'FMX', 'GER_ESTGANPER_ANUAL_REAL', '4', null);


select *
  from sistabgen
 where sistabcod = 500
   and sisdatcod = 170
 order by sisdatcod;


-- form name
-- REP_ESTADO_RESULTADO_GERENCIAL