select *
  from usuario_modulo
 where modulo in ('EMITE_OP')
 and usuario not in ('PEVISA')
 order by usuario, modulo;

select * from modulo;

INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('ALBERTO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('APINEDO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('CNAVARRO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('CNINAMANGO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('CUSURIAGA', 'EMITE_OP_LIMITE', 'SI', 'SI');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('DNUNEZM', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('DVILLACRESIS', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('FELIPE_CRUZ', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('GPALOMINO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('HAPARCANA', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('HOLIVARES', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('HREMUZGO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('ISAIAS_MECHATO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JACUNA', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JCABEZAS', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JJUAREZ', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JMENDEZ', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JOSORIO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JPOZO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JQUISPEB', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JVASQUEZ', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('JVILLON', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('KCASTILLO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('MARONES', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('MDIAZH', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('MSOTOMAYOR', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('NBELANDRIA', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('NYABAR', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('OMAR_TORRES', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('PEVISA', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('RICARDO_TOVAR', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('SCASTRO', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('SVARGAS', 'EMITE_OP_LIMITE', 'NO', 'NO');
INSERT INTO PEVISA.USUARIO_MODULO (USUARIO, MODULO, MAESTRO, SUPERMAESTRO) VALUES ('VREYMUNDO', 'EMITE_OP_LIMITE', 'NO', 'NO');